Endpoint delete book with isbn
NightTheo/shelf pull request #23
Opened 2022-02-01 14:08 UTC by Nathan-dev-dot

2022-02-01 14:38 UTC, NightTheo approved these changes

2022-02-01 18:35 UTC, Pbonnamy requested changes

2022-02-01 18:35 UTC, Pbonnamy commented on src/books/persistence/book.repository.imp.ts
> +    async delete(isbn: string): Promise<void> {
Plutot un type Isbn pour le isbn (à la place du string)

2022-02-01 18:59 UTC, Pbonnamy approved these changes

2022-02-01 22:16 UTC, NightTheo commented
Il y a deux problèmes: 
- si l'isbn donné dans l'url n'est pas dans le bon format, le code d'erreur est 500, il devrait être **404 not found**. Il faut utiliser le filtre `BookExceptionFilter` sur la route delete.
- En cas de réussite l'api renvoie le code 200 OK, il devrait renvoyer **204 no content**.

2022-02-04 09:55 UTC, Pbonnamy approved these changes

2022-02-04 16:02 UTC, NightTheo approved these changes

2022-02-04 16:02 UTC, merged